<a href="https://colab.research.google.com/github/baranwal123/my-python-work/blob/main/assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. (Scenario) You receive a CSV file with missing values and inconsistent date
formats. Write a program to clean and standardize the dataset using pandas and
datetime.
Hint: Hint: Use pandas.read_csv(), fillna(), and pd.to_datetime().

In [1]:
import pandas as pd

data = {
    'name': ['A', 'B', 'C', 'D'],
    'date': ['12/04/2024', '2024-04-13', 'April 14 2024', None],
    'value': [10, None, 30, 40]
}

df = pd.DataFrame(data)

df.fillna(method='ffill', inplace=True)

df['date'] = pd.to_datetime(df['date'], errors='coerce')

df['date'] = df['date'].dt.strftime('%Y-%m-%d')

df.to_csv("cleaned_data.csv", index=False)

print(df)

  name        date  value
0    A  2024-12-04   10.0
1    B         NaN   10.0
2    C         NaN   30.0
3    D         NaN   40.0


/tmp/ipykernel_19411/2248956463.py:11: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)


2. Write a NumPy function to normalize an array using min-max scaling.
Hint: Hint: (x - min) / (max - min)

In [4]:
import numpy as np

def normalize(arr):
    arr = np.array(arr)
    return (arr - arr.min()) / (arr.max() - arr.min())

data = [10, 20, 30, 40, 50]

result = normalize(data)

print(result)

[0.   0.25 0.5  0.75 1.  ]


3. (Scenario) You are given logs with timestamps in different formats. Extract and
convert them into a standard datetime format.
Hint: Hint: Use datetime.strptime() and regex.

In [3]:
import re
from datetime import datetime

logs = [
    "Error 12/04/2024 10:30:00",
    "Warning 2024-04-13 11:45:00",
    "Info April 14 2024 12:00:00"
]

formats = ["%d/%m/%Y %H:%M:%S", "%Y-%m-%d %H:%M:%S", "%B %d %Y %H:%M:%S"]

result = []
for log in logs:
    date_str = re.search(r'(\d{2}/\d{2}/\d{4} \d{2}:\d{2}:\d{2}|\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}|[A-Za-z]+ \d{1,2} \d{4} \d{2}:\d{2}:\d{2})', log).group(0)
    for f in formats:
        try:
            result.append(datetime.strptime(date_str, f).strftime("%Y-%m-%d %H:%M:%S"))
            break
        except:
            pass

print(result)

['2024-04-12 10:30:00', '2024-04-13 11:45:00', '2024-04-14 12:00:00']


4. Write a regex pattern to validate an Indian phone number.
Hint: Hint: Starts with +91 or 10 digits.

In [5]:
import re

def validate_phone(number):
    pattern = r'^(\+91[\-\s]?)?[6-9]\d{9}$'
    return bool(re.match(pattern, number))

numbers = ["9876543210", "+919876543210", "+91 9876543210", "1234567890"]

for num in numbers:
    print(num, validate_phone(num))

9876543210 True
+919876543210 True
+91 9876543210 True
1234567890 False


5. (Scenario) You need to find duplicate records based on multiple columns in a
dataset.
Hint: Hint: Use pandas.duplicated(subset=...).

In [6]:
import pandas as pd

data = {
    'name': ['A', 'B', 'A', 'C', 'B'],
    'age': [20, 25, 20, 30, 25],
    'city': ['X', 'Y', 'X', 'Z', 'Y']
}

df = pd.DataFrame(data)

duplicates = df[df.duplicated(subset=['name', 'age'])]

print(duplicates)


  name  age city
2    A   20    X
4    B   25    Y


6. Write a function to handle file not found errors gracefully.
Hint: Hint: Use try-except with FileNotFoundError.

In [10]:
with open("data.txt", "w") as f:
    f.write("shlok baranwal")

In [11]:
def read_file(filename):
    try:
        with open(filename, 'r') as f:
            return f.read()
    except FileNotFoundError:
        return "File not found. Please check the filename."

print(read_file("data.txt"))

shlok baranwal


7. Create a NumPy array and compute mean, median, and standard deviation.
Hint: Hint: np.mean(), np.median(), np.std().

In [12]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

30.0
30.0
14.142135623730951


8. (Scenario) Extract all email addresses from a text file.
Hint: Hint: Use regex with pattern for emails.

In [16]:
with open("data.txt", "w") as f:
    f.write("my mail is test@gmail.com and second mail is abc123@yahoo.com and my personal mail is baranwal1008@gmail.com")

In [17]:
import re

def extract_emails(filename):
    try:
        with open(filename, 'r') as f:
            text = f.read()

        pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
        emails = re.findall(pattern, text)

        return emails

    except FileNotFoundError:
        return "File not found"

print(extract_emails("data.txt"))

['test@gmail.com', 'abc123@yahoo.com', 'baranwal1008@gmail.com']


9. Write a program to read a file and count word frequency.
Hint: Hint: Use dictionary and split().

In [18]:
with open("data.txt", "w") as f:
    f.write("apple banana apple mango banana apple")

In [19]:
def word_frequency(filename):
    with open(filename, 'r') as f:
        text = f.read().lower()

    words = text.split()

    freq = {}

    for word in words:
        freq[word] = freq.get(word, 0) + 1

    return freq

print(word_frequency("data.txt"))

{'apple': 3, 'banana': 2, 'mango': 1}


10. Convert a string date into datetime and extract year, month, day.
Hint: Hint: datetime.strptime().

In [20]:
from datetime import datetime

date_str = "13/04/2024"

dt = datetime.strptime(date_str, "%d/%m/%Y")

print(dt.year)
print(dt.month)
print(dt.day)

2024
4
13


11. (Scenario) You need to process a large log file line by line efficiently.
Hint: Hint: Use file iteration instead of read().

In [24]:
with open("log.txt", "w") as f:
    f.write("Error: server down\n")
    f.write("Warning: high CPU usage\n")
    f.write("Info: system restarted\n")

In [23]:
def process_log(filename):
    with open(filename, 'r') as f:
        for line in f:
            print(line.strip())

process_log("log.txt")

Error: server down
Info: system restarted


12. Write regex to extract all numbers from a string.
Hint: Hint: Use \d+

In [25]:
import re

text = "My age is 21 and I have 2 bikes and 300 rupees"

numbers = re.findall(r'\d+', text)

print(numbers)

['21', '2', '300']


13. Handle multiple exceptions in Python.
Hint: Hint: except (TypeError, ValueError):

In [1]:
def divide_numbers(a, b):
    try:
        result = a / b
        print(result)
    except (TypeError, ValueError):
        print("Invalid input type")
    except ZeroDivisionError:
        print("Cannot divide by zero")

divide_numbers(10, 0)
divide_numbers(10, "2")
divide_numbers(10, 2)

Cannot divide by zero
Invalid input type
5.0


14. (Scenario) A NumPy array contains NaN values. Replace them with column
mean.
Hint: Hint: np.nanmean().

In [2]:
import numpy as np

arr = np.array([
    [10, np.nan, 30],
    [40, 50, np.nan],
    [70, 80, 90]
])

col_mean = np.nanmean(arr, axis=0)

for i in range(arr.shape[1]):
    arr[:, i] = np.where(np.isnan(arr[:, i]), col_mean[i], arr[:, i])

print(arr)


[[10. 65. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]


15. Write a program to append data into a file without overwriting.
Hint: Hint: Use &#39;a&#39; mode.

In [3]:
def append_to_file(filename, text):
    with open(filename, 'a') as f:
        f.write(text + "\n")

append_to_file("data.txt", "This is new line 1")
append_to_file("data.txt", "This is new line 2")

with open("data.txt", "r") as f:
    print(f.read())

This is new line 1
This is new line 2



16. Convert a list into a NumPy array and reshape it.
Hint: Hint: np.array().reshape().

In [4]:
import numpy as np

lst = [1, 2, 3, 4, 5, 6]

arr = np.array(lst).reshape(2, 3)

print(arr)

[[1 2 3]
 [4 5 6]]


17. (Scenario) Parse a log file and extract IP addresses.
Hint: Hint: Regex for IP pattern.

In [6]:
with open("log.txt", "w") as f:
    f.write("User login from 192.168.1.1\n")
    f.write("Request came from 10.0.0.5\n")
    f.write("Error from 192.168.1.1\n")
    f.write("Access from 172.16.0.2\n")

In [7]:
import re

def extract_ips(filename):
    try:
        with open(filename, 'r') as f:
            text = f.read()

        pattern = r'\b(?:\d{1,3}\.){3}\d{1,3}\b'
        return re.findall(pattern, text)

    except FileNotFoundError:
        return "File not found"

print(extract_ips("log.txt"))

['192.168.1.1', '10.0.0.5', '192.168.1.1', '172.16.0.2']


18. Write a custom exception class.

Hint: Hint: class MyError(Exception)::

In [8]:
class MyError(Exception):
    pass

def check_age(age):
    if age < 18:
        raise MyError("Age must be 18 or above")
    else:
        print("Valid age")

try:
    check_age(15)
except MyError as e:
    print(e)

Age must be 18 or above


19. Compare two dates and find difference in days.
Hint: Hint: timedelta.

In [9]:
from datetime import datetime

date1 = datetime.strptime("01/04/2024", "%d/%m/%Y")
date2 = datetime.strptime("13/04/2024", "%d/%m/%Y")

diff = date2 - date1

print(diff.days)

12


20. (Scenario) You receive corrupted file input. Ensure your program doesn&#39;t
crash.
Hint: Hint: Use try-except-finally.

In [10]:
with open("data.txt","w") as f: f.write("hello\nfile test")

try:
    f=open("data.txt")
    print(f.read())
except:
    print("Error")
finally:
    f.close()

hello
file test


21. Write regex to validate password with constraints.
Hint: Hint: Use lookahead assertions.

In [11]:
import re

def validate_password(pw):
    pattern = r'^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*?&]).{8,}$'
    return bool(re.match(pattern, pw))

print(validate_password("Abc@1234"))
print(validate_password("hello123"))

True
False


22. Save and load NumPy arrays to file.
Hint: Hint: np.save(), np.load().

In [12]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

np.save("array_file.npy", arr)

loaded_arr = np.load("array_file.npy")

print(loaded_arr)

[10 20 30 40 50]


23. (Scenario) Extract date from filenames and sort files.
Hint: Hint: Use regex + datetime.

In [13]:
import re
from datetime import datetime

files = [
    "report_12-04-2024.txt",
    "report_01-04-2024.txt",
    "report_13-04-2024.txt"
]

def sort_files(file_list):
    data = []

    for file in file_list:
        date_str = re.search(r'\d{2}-\d{2}-\d{4}', file).group()
        date_obj = datetime.strptime(date_str, "%d-%m-%Y")
        data.append((date_obj, file))

    data.sort()
    return [file for date, file in data]

print(sort_files(files))

['report_01-04-2024.txt', 'report_12-04-2024.txt', 'report_13-04-2024.txt']


24. Write a generator to read large files efficiently.
Hint: Hint: yield keyword.

In [14]:
def read_large_file(filename):
    with open(filename, "r") as f:
        for line in f:
            yield line.strip()

for line in read_large_file("data.txt"):
    print(line)

hello
file test


25. (Scenario) Convert timestamps from UTC to IST.
Hint: Hint: Use datetime + timezone.

In [1]:
from datetime import datetime, timezone, timedelta

utc_time = datetime(2024, 4, 13, 10, 0, 0, tzinfo=timezone.utc)

ist = timezone(timedelta(hours=5, minutes=30))

ist_time = utc_time.astimezone(ist)

print("UTC Time:", utc_time)
print("IST Time:", ist_time)

UTC Time: 2024-04-13 10:00:00+00:00
IST Time: 2024-04-13 15:30:00+05:30
